apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base

# For some of the configmaps and secrets we could use suffix hash,
# but some will be used directly by prow, which cannot know about
# the suffix. So we disable it.
generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - plugins.yaml
  name: plugins
  namespace: prow
- files:
  - config.yaml
  name: config
  namespace: prow
- files:
  - labels.yaml
  name: label-config
  namespace: prow