plugins:
  calf-nursery:
    plugins:
    - approve
    - assign
    - blunderbuss
    - cat
    - dog
    - help
    - heart
    - hold
    - label
    - lgtm
    - trigger
    - verify-owners
    - wip
    - yuks
  calf-nursery/test-infra:
    plugins:
    - config-updater

approve:
- repos:
  - calf-nursery/testapp
  # RequireSelfApproval requires PR authors to explicitly approve their PRs.
  # Otherwise the plugin assumes the author of the PR approves the changes in the PR.
  require_self_approval: true

  # A /lgtm from a single approver should not allow a PR to merge.
  lgtm_acts_as_approve: false

external_plugins:
  calf-nursey:
  - name: needs-rebase
    events:
      - issue_comment
      - pull_request

config_updater:
  maps:
    config/prow/config.yaml:
      name: config
    config/prow/plugins.yaml:
      name: plugins
    config/prow/labels.yaml:
      name: label-config
    jobs/**/*.{yaml,yml}:
      name: job-config
      gzip: true