plugins:
  calf-nursery:
    plugins:
    - approve
    - assign
    - blunderbuss
    - cat
    - dog
    - help
    - heart
    - hold
    - label
    - lgtm
    - trigger
    - verify-owners
    - wip
    - yuks
  calf-nursery/test-infra:
    plugins:
    - config-updater

config_updater:
  maps:
    jobs/**/*.{yaml,yml}:
      name: job-config
      gzip: true