plugins:
  calf-nursery:
    plugins:
    - approve
    - assign
    - blunderbuss
    - cat
    - dog
    - help
    - heart
    - hold
    - label
    - lgtm
    - trigger
    - verify-owners
    - wip
    - yuks
  calf-nursery/test-infra:
    plugins:
    - config-updater

external_plugins:
  calf-nursey:
  - name: needs-rebase
    events:
      - issue_comment
      - pull_request

config_updater:
  maps:
    config/prow/config.yaml:
      name: config
    config/prow/plugins.yaml:
      name: plugins
    config/prow/labels.yaml:
      name: label-config
    jobs/**/*.{yaml,yml}:
      name: job-config
      gzip: true